package com.rg.krg13_dev.autocomputer

enum class AcRequest(val code: Int) {
    REQ_STATUS(0x01),
    REQ_CURRENT_DATE_TIME(0x02),
    REQ_PRINTER_CHARACTER(0x03),
    REQ_CLEAR_TICKET_COUNTER(0x04),
    REQ_LOCK_KRG(0x05),
    REQ_UNLOCK_KRG(0x06),
    REQ_READ_SOFTWARE_VERSION(0x07),
    REQ_SAVE_COURSE_PARAMETER(0x08),
    REQ_SAVE_STOPS_LIST(0x09),
    REQ_READ_REPORT(0x0A),
    REQ_DELETE_READ_REPORT(0x0B),
    REQ_SAVE_TARIFF_TABLE(0x0C),
    REQ_SAVE_BLACK_LIST(0x0D),
    REQ_READ_TOPUP_CARD_NUMBER(0x0E),
    REQ_PROGNATURAL(0x0F),
    REQ_SAVE_TOPUP_TRANSACTION(0x10),
    REQ_SAVE_BLACK_FILE(0x11),
    REQ_READ_CARD_NUMBER_INFO(0x12),
    REQ_SAVE_CARD_INFO(0x13),
    REQ_END_COURSE(0x14),
    REQ_SAVE_TOKEN_LIST(0x15),
    REQ_TRANSFER_TOKEN_LIST(0x16),
    REQ_SAVE_RAIL_COURSE_PARAMETER(0x17),
    REQ_RESTART_ME(0x18),
    REQ_SAVE_TARIFF_CSV_TABLE(0x19),
    REQ_DIAGNOSTIC(0x1A),
    REQ_TRANSFER_USED_TICKET(0x1B);

    companion object {
        fun fromCode(code: Int): AcRequest? = values().find { it.code == code }
    }
}
