package com.rg.krg13_dev.autocomputer

enum class StatusFlag(val bitPosition: Int) {
    DEVICE_LOCKED(31),
    REQUEST_FOR_LOCK(30),
    REQUEST_FOR_UNLOCK(29),
    REQUEST_FOR_REPORT_READING(28),
    REQUEST_FOR_CARD_NUMBER_READING(27),
    REQUEST_FOR_INFORMATION_ON_CARRIAGE(26),
    MISSING_RAIL_COURSE_PARAMETERS(10),
    MISSING_COLOR_LIST(9),
    MISSING_STOP_LIST(8),
    MISSING_BLACKLIST(7),
    MISSING_TARIFF_TABLE(6),
    MISSING_COURSE_PARAMETERS(5),
    DAMAGED_MIFARE_SYSTEM_OR_SELF(4),
    DAMAGED_PRINTER(3),
    BLOCKED_SLOT(2),
    MISSING_DATA_FOR_PRINTING(1),
    MISSING_CURRENT_TIME_DATA(0)
}
